CREATE TABLE Persons
( 
	ID numeric(10) GENERATED BY default on null as IDENTITY,
	LastName varchar2(255) NOT NULL,
	FirstName varchar2(255),
	Age numeric(10),
	CONSTRAINT ID_pk PRIMARY KEY (ID)
);

CREATE TABLE Jobs (
    PersonID numeric(10) NOT NULL,
	PositionID numeric(10),
    Description varchar2(255),
    Location varchar2(255),
	CONSTRAINT fk_PersonID
		FOREIGN KEY (PersonID)
		REFERENCES Persons(ID)
);
